# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np
x = (6*np.ones((5,5),dtype=int))
print(x)
print('6 on the border and 0 inside in the array-\n')
x[1:-1,1:-1]=0
print(x)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
6 on the border and 0 inside in the array-

[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
import numpy as np
print("Checkerboard pattern:")
x = 3*np.ones((8,8),dtype=int)
x[1::2,::2] = 9
x[::2,1::2] = 9
print(x)

Checkerboard pattern:
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
import numpy as np
x=np.empty((3,4))
print(x)
print(np.full((3,3),6))

[[1.29880910e+219 7.48956328e+247 7.01926395e+078 6.37748939e-047]
 [1.30741258e+079 6.50751136e+029 1.37949241e+219 3.68415081e+180]
 [1.82102974e+098 1.75983383e+112 1.76966550e-061 2.57206528e+064]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
arr1 = np.array([0,12,45.21,34,99.91])
print('Sample Array -',arr1)
#arr1 = (arr1 - 32) * (5/9)
#print(arr1)
print(list(map(lambda x:(x-32)*(5/9),arr1)))
fah=[(x-32)*(5/9) for x in arr1]
print(fah)

Sample Array - [ 0.   12.   45.21 34.   99.91]
[-17.77777777777778, -11.11111111111111, 7.3388888888888895, 1.1111111111111112, 37.727777777777774]
[-17.77777777777778, -11.11111111111111, 7.3388888888888895, 1.1111111111111112, 37.727777777777774]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [5]:
arr1 = np.array(1+0j)
arr2 = np.array(0.70710678+0.70710678j)
print('Real part of the array: ',arr1.real,arr2.real)
print('Imaginary part of the array:', arr1.imag,arr2.imag)

Real part of the array:  1.0 0.70710678
Imaginary part of the array: 0.0 0.70710678


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [6]:
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([0,40])
print(np.in1d(arr1,arr2))

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [7]:
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([10,30,40])
print('Array 1: ',arr1)
print('Arrary2: ',arr2)
print('Common values between two arrays-\n',np.intersect1d(arr1,arr2))

Array 1:  [ 0 10 20 40 60]
Arrary2:  [10 30 40]
Common values between two arrays-
 [10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [8]:
arr1 = np.array([10,10,20,20,30,30])
print('Original array-\n',arr1)
print('Unique elements of the above array-\n',np.unique(arr1))
arr2 = np.array([[1,1],[2,3]])
print('Original array-\n',arr2)
print('Unique elements of the above array-\n',np.unique(arr2))

Original array-
 [10 10 20 20 30 30]
Unique elements of the above array-
 [10 20 30]
Original array-
 [[1 1]
 [2 3]]
Unique elements of the above array-
 [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [9]:
arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([10,30,40,50,70])
print('Unique values that are in only one (not both) of the input arrays- \n',np.setxor1d(arr1,arr2))

Unique values that are in only one (not both) of the input arrays- 
 [ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [10]:
print(np.all([10,20,30,0]))
print(np.all([[True,False],[False,True]]))
print(np.all([[True,True],[True,True]]))

False
False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [11]:
print(np.any([10,20,30,0]))
print(np.any([[True,False],[False,True]]))
print(np.any([[True,True],[True,True]]))
print(np.any([[False,False],[False,False]]))

True
True
True
False


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [12]:
arr1 = np.array([1,2,3,4])
print('Repeating 2 times \n', np.tile(arr1, 2))
print('Repeating 3 times \n', np.tile(arr1, 3))

Repeating 2 times 
 [1 2 3 4 1 2 3 4]
Repeating 3 times 
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [13]:
arr1 = np.array([1,2,3,4,5,6])
print('Maximum Values- :',np.argmax(arr1))
print('Minimum Values- :',np.argmin(arr1))

Maximum Values- : 5
Minimum Values- : 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [14]:
a = np.array([1,2])
b = np.array([4,5])
print('Array a-',a)
print('Array b-',b)
print("a > b")
print(a > b)
print("a >= b")
print(a >=b)
print("a < b")
print(a<b)
print('a <= b')
print(a<=b)

Array a- [1 2]
Array b- [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [15]:
arr1 = np.array([[4,6],[2,1]])
print('Original array: \n',arr1)
x=np.sort(arr1,axis=0)
print('Sort along the first axis: \n',x)
print('Sort along the last axis: \n',np.sort(x,axis=1))

Original array: 
 [[4 6]
 [2 1]]
Sort along the first axis: 
 [[2 1]
 [4 6]]
Sort along the last axis: 
 [[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [16]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [17]:
arr1 = np.array([[0,10,20],
                [20,30,40]])
print('original array: \n',arr1)
print('Greater than 10 is \n',arr1[arr1>10])
print('Their indices are \n',np.nonzero(arr1>10))

original array: 
 [[ 0 10 20]
 [20 30 40]]
Greater than 10 is 
 [20 20 30 40]
Their indices are 
 (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [18]:
import numpy as np
arr1=np.ones((4,4))
print(arr1.dtype)
print('Item Size: ',arr1.itemsize)
print('Array size: ',arr1.size)
print('Byte size: ',arr1.size * arr1.itemsize)
#print(arr1)

float64
Item Size:  8
Array size:  16
Byte size:  128


## Great Job!